### ISSUE TITLE
Load More Button not working properly when there's no pageSize querystring

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/product-list#6]
The Load More button doesn't work the first time you click it — there is, when there's no `pageSize` querystring on the URL.  If you add, for example `pageSize=5` by hand on the URL it will work properly, adding 5 more products, but out of the gate it doesn't work.

There's alsoo the need to show a message when there are no more products to be loaded. Do you think you can add this message to the component's logic, @tamorim? It's really important for the button to be usable — I could style it quickly afterwards.

**Comment by tamorim** [comment]
The thing is: it should always be accessed with pageSize. without pageSize the request goes without the number and brings everything (or the default pagination).

If accessed without pageSize it shouldn't even appear the button, or we do some treatment to append the pageSize querystring.

With resourceBinding that gets a little difficult on the first load, but if we do when the route changes, it may cause double loading... could be tricky.

**Comment by dfosco** [comment]
I'm not sure I follow. The first time the page is loaded, it comes with 10 products with URL as:

```
http://dreamstore.local.myvtex.com:3000/feminino/c
```

When you click the button for the first time, the URL changes to:

```
http://dreamstore.local.myvtex.com:3000/feminino/c?pageSize=NaN
```

And no other products are loaded. What should be the default behavior, then?

**Comment by dfosco** [comment]
Closed and tested. Thanks @tamorim!
